### ISSUE TITLE
Heater for lens

### ISSUE THREAD

**Issue by VojislavM** [IRNAS/koruza-compute-module#26]
Add one MOSFET output for heater...

**Comment by SloMusti** [comment]
via optocopupler for full isolation as we will use input voltage directly

**Comment by VojislavM** [comment]
This will be a resistor around 5W
power voltage is 24V so the current will be around 0.208A, and the value of the resistor should be around 115 Ohm

This will be turned on and off over FET with opto isolation

**Comment by VojislavM** [comment]
![image](https://user-images.githubusercontent.com/8199477/29614680-66466b0c-880b-11e7-8678-72bd1b4111ec.png)
