### ISSUE TITLE
Add LED disable transistor

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/koruza-compute-module#29]
Add transistor such that all LEDs inside can be disabled, except ethernet port diodes. This prevents from extra light exitign the unit when not needed.

**Comment by VojislavM** [comment]
the diodes will be switched with one [MOSFET](http://uk.farnell.com/nxp/nx7002bk/mosfet-n-ch-60v-0-27a-sot-23-3/dp/2469640?ost=2469640&searchView=table&iscrfnonsku=false&ddkey=http%3Aen-GB%2FElement14_United_Kingdom%2Fsearch)

**Comment by VojislavM** [comment]
there are two diodes and they are turned off with separate mosfets Q4 and Q5, but with the same pin. Default state is on which is provided by the pull up resistor R64. 

![image](https://user-images.githubusercontent.com/8199477/29606195-d6064c5a-87ed-11e7-9092-90b720ad023f.png)
